@baseUrl = http://localhost:8080/films

### Read All films
GET {{baseUrl}}

###
GET {{baseUrl}}/4

###
GET {{baseUrl}}/10

###
GET {{baseUrl}}?minimum-duration=160

### Create One film
POST {{baseUrl}}
Content-Type: application/json

{
  "title" : "Venom: Let There Be Carnage",
  "duration" : 97,
  "budget" : 110,
  "link" : "https://en.wikipedia.org/wiki/Venom:_Let_There_Be_Carnage"
}
### Update One film
PUT {{baseUrl}}/1
Content-Type: application/json

{
  "title" : "Venom: Let There Be Carnage",
  "duration" : 1,
  "budget" : 110,
  "link" : "https://en.wikipedia.org/wiki/Venom:_Let_There_Be_Carnage"
}
### Delete one film
DELETE {{baseUrl}}/5